model_list:
  - model_name: "default"
    litellm_params:
      model: "ollama/qwen2.5:3b"
      api_base: "http://localhost:11434"

  - model_name: "gpt-4.1-mini"
    litellm_params:
      model: "ollama/qwen2.5:3b"
      api_base: "http://localhost:11434"

litellm_settings:
  set_verbose: false
  drop_params: true
